name: cv_assignment

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.12
  - hydra-core=1.1.1
  - yapf=0.32.0
  - opencv=4.5.5
  - scikit-learn=1.0.2
  - matplotlib=3.5.1
  - absl-py=1.0.0
  - protobuf=3.19.4
  - pandas=1.4.1
  - tqdm=4.63.0
  - pytorch=1.10.2
  - seaborn=0.11.2
  - torchvision=0.11.3
  - pip=20.3.3
  - pip:
    - tensorflow==2.8.0
    - matplotlib-inline==0.1.3
    - Pillow>=7.1.2
    - PyYAML>=5.3.1
    - requests>=2.23.0
    - scipy>=1.4.1
